### ISSUE TITLE
Reaching out hand

### ISSUE THREAD

**Issue by Bobster82** [jtsage/FS22_simpleInspector#10]
Hey,

Not a bug or feature, but a reaching out hand ;)

I made my own version of this mod too a while back, but due some issues (not mod based, but giants) I stopped working on my version. You can use any feature of my version or copy stuff if you want/like. I do want to mention: Im not a programmer, so its pretty basic in some ways ;) But I also wrote this mod in first place for private use.

This is the link:
https://github.com/Bobster82/FS22_VehicleInfo

Cheers, 
Bob

**Comment by jtsage** [comment]
Hey, thanks for the heads up - I do appreciate it.  I've by no means abandoned this one, but it pretty much does exactly what I want for the time being, just sort of watching to make sure nothing breaks with updates, and the occasional feature request I think is worthwhile :)
