### ISSUE TITLE
order the text as we want

### ISSUE THREAD

**Issue by yann-mrt** [jtsage/FS22_simpleInspector#11]
Good day,
Can we have the posisibility to be able to order the text as we want ?
For example, i would like to have the name of the equipment first then the speed then....
If we could order the string as we want int the FS22_SimpleInspectorSettings.xml it could be great.
Thanks for your time

**Comment by jtsage** [comment]
Hmm.  that is not the worst idea I ever heard. lemme think over a bit how to do it.  But yeah, I like this idea.  $real_life is kicking my butt just a bit right now, give me a week or two to get something worked up.

**Comment by yann-mrt** [comment]
That's great thanks. Take your time, I'm sure I can survive without for few weeks :o)))

**Comment by jtsage** [comment]
I didn't push a real release yet, but initial support added to the zip in the repo.

Not totally supported yet, but in the xml settings you will find __displayOrder__ - the options are

* __SPD__ - speed
* __GAS__ - fuel level
* __DAM__ - damage indicator (if applicable)
* __FLD__ - on-field status
* __AIT__ - AI worker tag
* __USR__ - User worker tag
* __VEH__ - Vehicle name
* __FIL__ - Fill Levels
* __SEP__ - Forced separator

_You must use a single underscore between terms!!_

Default: `SPD_GAS_DAM_FLD_AIT_USR_VEH_FIL`

I still need to re-work how separators work, as they might appear in odd places or not at all when
you re-order, hence the addition of __SEP__ to force one.

**Comment by yann-mrt** [comment]
Not sure why but I don't have the displayOrder appearing in the FS22_SimpleInspectorSettings.xml.
As well I have <version string="1.0.0.4"/> but I'm running the last one (that is on the main branch). Look like the xml is not updated.
As well 2 : I notice my path is not modSettings/FS22_SimpleInspector/savegame##/simpleInspector.xml but modSettings/FS22_SimpleInspector/simpleInspector.xml. (missing savegame##).

**Comment by jtsage** [comment]
lemme make sure I didn't screw up the zip file, probably did.

but in the meantime, (and you might wanna backup first) - what happens if you go to modSettings/FS22_SimpleExplorer - because apparently I forgot the name of my own mod...  (i'll fix this too in the next release.  which is a pain, cause it's going to lose all the current settings... sigh.)  You could also try nuking that modSettings/FS22_Simple...  folder and see if it re-creates with the savegame.

**Comment by jtsage** [comment]
Yeah, some of the elements have a built in seperator, some do not. I think best use case would be for me to get rid of them in the existing elements and update the "default" to put them back in the default places.  The only element that adds them conditionally is the fill levels (it should put them between types).

As to the fuel level, you do - D:63% (63% full of diesel).  You may be confusing it with damage, which, if memory serves shows a bright red double exclamation point when something is really, really damaged (80% damage / 20% remaining)

When I fix the name of that settings folder, I'm going to add a bit that will clean up the old ones (basically load them once, save the new file, and ignore it forever more).  I could probably add an option to prefer a "global" config if you'd like - the use case for the savegame bit was pretty much I want a whole lot more info when I am in single player vs. the once in a blue moon when I do MP.

**Comment by yann-mrt** [comment]
Sorry for the late answer.
I like the separator, it is just that some time when their is no separator it should be some space I think. The "problem" is when damage is not showing anything their is double separator. 

For the fuel, I catch it now. Thanks

Yep for MP make sense to have different setting, but yes i guess ... for me... it could make sense to have option for global or not.

**Comment by jtsage** [comment]
So, gonna push my update in a bit - but basically, I dropped all the "forced" separators in the code block - the new default is:

`SPD_SEP_GAS_SEP_DAM_FLD_AIT_USR_VEH_FIL`

Of special note, there is now a `DAM*` option - it's the same as `DAM`, but if something is damaged enough to add the marker, it will *also* add an extra separator after it.  

Similar to that, added a `AIT*`, `USR*` and `FLD*` option

Still thinking through the global config option.
