### ISSUE TITLE
Fill level display color issue with 2 tanks.

### ISSUE THREAD

**Issue by daFreeMan** [jtsage/FS22_simpleInspector#14]
**Describe the bug**
When using a sprayer with a separate tank, when the sprayer's tank is empty and it switches to showing only the contents of the add-on tank, it displays the volume and `(100%)` but it shows them in red, not green. This also happens when filling the add-on tank first.

**To Reproduce**
* Purchase a John Deere R732i PowrSprayer (part of the Precision Farming mod)
* Purchase a HARDI 1200l Tank (base-game)
* Go to a fertilizer or herbicide filling station
* Fill the HARDI. 
   * It will show `1500 (100%)` in red text
* Start filling the JD R732i's tank, it will change to a shade of green.

**Expected behavior**
Any time it's displaying a fill level at 100%, I'd expect to see it in green

**Screenshots**
When spraying, it had just emptied the sprayer's tank and was 1 liter into the HARDI:
![image](https://user-images.githubusercontent.com/11889733/180333079-26db114a-c83c-481d-951a-ae8d535373bb.png)
Note the JCB 8330

100 liters of use into the add on tank, it was showing 94% remaining, but in a "warning orange", not a shade of green:
![image](https://user-images.githubusercontent.com/11889733/180333142-10f2dc9a-1cdc-4fa3-bb3c-0275aae41637.png)
Note the 2nd JCB 4220

Yes, both tractors were equipped with the same sprayer/add-on tank combo.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version
    - FS22: 1.6.0.0
    - SimpleInspector: v1.0.1.6 

**Additional context**
Haven't tried it with any other combination of sprayer/add-on tank, so it _could_ be specific to this pair.
Not a critical issue, but it was disconcerting to see it suddenly go red when it had been a yellow/orange color (1500 l add on, plus 3360 l main tank = 4860 total capacity, so it was showing ~31% left when it switched tanks). I had to squint at it to ensure that it wasn't actually 0%, because this was my first time using this combo and I wasn't 100% certain that the sprayer would actually draw from the extra tank, so I was keeping an eye on it.

**Comment by jtsage** [comment]
Let me see what I can do - I didn't open up that tank specifically yet, but the issue is it only "flips" the fill color in specific circumstances - if you have a tank trailer of liquid fertilizer, are you just transporting it somewhere (so red 100% makes sense, like all the grain works), or is it hooked to a sowing machine / sprayer and green 100% makes sense?  It's pretty difficult to tell at the script level.  But, I'll take a look and see if there is some sort of hint I missed.

**Comment by daFreeMan** [comment]
I see the point that it may be hard to determine the difference. The code is _definitely_ seeing this as a "transport device" where 100% is full and you can't load any more into it. I hadn't looked at it from that perspective...

Honestly, I'd seen in the notes about the colors changing and was confused, but it makes perfect sense - I want 100% to be red when my harvester is full, but green when the fertilizer sprayer is full.

**Comment by daFreeMan** [comment]
An additional data point: 

All 3 of these tractors have the exact same setup with the JD sprayer on the back and the HARDI tank on the front. At _some_ point, it's switching from more is a red highlight to more is a green highlight. You can see the top one is at 88% and listed in green, while the bottom two are 90%+ and orange/red.

![image](https://user-images.githubusercontent.com/11889733/180657519-c2a36782-760f-4a0a-a1f4-43f3f5a42892.png)

**Comment by jtsage** [comment]
Got it, thanks.  I actually noticed the same with the DB120 that just dropped - I might go ahead and do the toggle based on the filltype instead - seeds/fert/herbicide/lime to 100% is "good".  I will investigate.

**Comment by jtsage** [comment]
Yeah, I did a terrible job of checking for which types should be inverted.  I just pushed a release canidate that should fix this. https://github.com/jtsage/FS22_simpleInspector/blob/e801611e387c80fceca3a4b5def3b3cd3ea71682/FS22_SimpleInspector.zip

**Comment by daFreeMan** [comment]
With just a full add-on tank:
![image](https://user-images.githubusercontent.com/11889733/181123912-b104def4-d368-4ae3-b360-61af144a56c0.png)

With the add-on tank and a partially filled sprayer:
![image](https://user-images.githubusercontent.com/11889733/181123945-0ef21e2c-4e35-46f4-b7d5-14921ab5dc06.png)

I'd say it looks good with this simple test.

**Comment by jtsage** [comment]
Cool.  so, the filltypes that always get flipped are:

``` text
  FillType.SEEDS,
  FillType.ROADSALT,
  FillType.FERTILIZER,
  FillType.LIME,
  FillType.SILAGE_ADDITIVE,
  FillType.LIQUIDFERTILIZER,
  FillType.HERBICIDE
```

And that's on top of the vehicle types that always get flipped (seeders, planters, water tankers, fuel tankers - things of that nature. Thanks for taking the time to help hunt this down!
