### ISSUE TITLE
DEF Fluid

### ISSUE THREAD

**Issue by tuzlo** [jtsage/FS22_simpleInspector#15]
This is not an issue more fo an enhancement

Along with "GAS" or Diesel is it possible to add a DEF display option?

**Comment by jtsage** [comment]
Yeah, I can do that.  It'll probably be added as an option, turned off by default, because it only really matters if you are using the DEF pack - otherwise, my understanding is that fill level follows fuel pretty closely.

**Comment by jtsage** [comment]
This will be in 1.0.1.9 - it's already in the ZIP file in the repo if you want to test it out.

**Comment by jtsage** [comment]
pushed to modhub, should be out in a few days.
