### ISSUE TITLE
AD and CP functions

### ISSUE THREAD

**Issue by regs1980** [jtsage/FS22_simpleInspector#19]
Is it possible to display AD and CP functions like waiting or blocking?

**Comment by jtsage** [comment]
Lemme look at this again in a few days - when I originally implemented the AD/CP stuff for this, those status were not yet available, they may be now.

**Comment by jtsage** [comment]
So, an update - I can (and will in the next few days) add the drive time remaining (AD), and the fieldwork time remaining (CP), but I've not found anywhere I can read a blocking or waiting state - without digging too deep, I suspect these were implemented at the AI level in FS19 and are done differently in 22.
