### ISSUE TITLE
Colorblind mode setting nowhere to be found

### ISSUE THREAD

**Issue by 97Lukas90** [jtsage/FS22_simpleInspector#20]
Hello, in your Github readme you talk about an availabe colorblind mode:

![image](https://user-images.githubusercontent.com/95321654/192106793-9ea6e286-7ba1-475d-9538-69f29db9bf13.png)

I can't find that setting, neither ingame or in the .xml thats created in the modSettings folder.

Greetings,
Lukas

**Comment by jtsage** [comment]
It's a base game setting, somewhere in the graphics settings as I recall? (But, it's not something I added, just something it uses)
