### ISSUE TITLE
Conflict with HUD from Precision Farming

### ISSUE THREAD

**Issue by KITT3000** [jtsage/FS22_simpleInspector#21]
When the SI HUD is set to the upper left corner, after hiding the help window with the Precision Farming mod active, the SimpleInspector HUD overlaps the PF HUD.

**Comment by jtsage** [comment]
Alas, after much, much digging when messing with ProductionInspector, I cannot for the life of me find anywhere that the height & visibility of that added info is accessible to me - I can detect if PF is loaded, and I can detect if the F1 menu is hidden or shown, but nothing beyond that.

If somebody else has any idea where it might be accessible, I'm all ears, but it's nowhere in `g_currentMission.inGameMenu.hud.inputHelp` or it's children (or it's parent come to that)

**Comment by jtsage** [comment]
Update: I found it.  I fixed it.  Woot.  This will be in the next released version (and is in the github latest relese)
