### ISSUE TITLE
Remaining time for CP Driver

### ISSUE THREAD

**Issue by Tensuko** [jtsage/FS22_simpleInspector#22]
**Is your feature request related to a problem? Please describe.**
As requested on our github Page, a small display for the remaining time.
Due to movable HUD, that doesn't fit for us, but may be a good addition for your mod.

**Describe the solution you'd like**
Maybe optional on/off. Totaly up to you :)

**Describe alternatives you've considered**
No need to implement it ofc, but I don't have an alternative solution :)

**Additional context**
Link to Issue from us, but I will close it as we won't add it on our side.
[#2241](https://github.com/Courseplay/Courseplay_FS22/issues/2241)

**Comment by jtsage** [comment]
Oh, good idea.  It has been my intent for a while to circle back to both CoursePlay and AutoDrive and see what additional information might be available that would make sense to display in simpleInspector.

Thanks

**Comment by jtsage** [comment]
As part of this, also add AD time remaining.  Dev notes for later:

`local cpStatus = thisVeh:getCpStatus()` (line 516)
`cpStatus:getTimeRemainingText()`  if not empty string

`thisVeh.ad.stateModule:isActive()` (line 510)
`thisVeh.ad.stateModule:getRemainingDriveTime()` if not zero

**Comment by jtsage** [comment]
Closing as complete - v1.0.2.0 on modHub.
