### ISSUE TITLE
Question, HUD visibility 

### ISSUE THREAD

**Issue by mrPassion78** [jtsage/FS22_simpleInspector#25]
Hi there, i was wondering if you could tell me what i need to change in order to have youre mod show all info, while i blendout my HUD.
even with everything blended out, i still would like to see if the hired worker of CP and AD, are not stopped and having a drink in the grass instead of working like they should :P LOL..

Could you help me with that please?

Thnx so much for the mod, time and effort 
Pascal

**Comment by jtsage** [comment]
I'm not sure I follow - you want to lose the rest of the HUD and keep the inspector?  It's not currently possible, and is unlikely to be added - but if you wanted to mess with it yourself, it would be one of the conditions on this line:

https://github.com/jtsage/FS22_simpleInspector/blob/26c70e1c30b07ad1d86d8b64343690eef55f0c11/src/SimpleInspector.lua#L602

Probably the two last ones, but there are a number of reasons that the HUD is turned off by the game where you won't want the inspector up (like in menus), and not really another place to check if those conditions are true.

**Comment by mrPassion78** [comment]
thnx, i will give it a try
