### ISSUE TITLE
[FEATURE] No-HUD mode

### ISSUE THREAD

**Issue by n4396t** [jtsage/FS22_simpleInspector#27]
Hi, I've been switched over to FS22 from FS17 for less than a year and I really like simple inspector but I was wondering if there is a way to have SI on the screen without having to put the whole HUD up?  I know I used glance in FS17 and it was only visible if the HUD wasn't and vice versa.  Can this be done in FS22?  OOPS!  Just saw that this was talked about only two or three days ago.  My Bad!!!
Thanks 
Mark

**Comment by jtsage** [comment]
As you noticed in #25, no, this is not currently possible.  Let me think some more on this and see what is possible.
