### ISSUE TITLE
[Question] Curious is the default font set to "bold"   ?     Could this be toggled on/off  in XML

### ISSUE THREAD

**Issue by BullFlag** [jtsage/FS22_simpleInspector#4]
[Question] Curious if the small font size would appear sharper ,  better looking with Bold OFF.   This is on a FS22 1080p resolution case
Great mod very well done!

**Comment by jtsage** [comment]
You are right, it does look better.  Like, much better.  But, adding the option anyway, default off.

**Comment by jtsage** [comment]
That fix is going to be in 1.0.0.5, which is actually in the zip file in the repo - tagged release in a few hours likely.
