### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by HurrycaneBE** [jtsage/FS22_simpleInspector#8]
Is it normal that you can only change display mode as admin on a dedi server ?

then , location will not be saved. on reconnect you must set it new.
 i dont have a log for you caused there is no bug in code it seems , nice job :)

**Comment by jtsage** [comment]
as in, a connected non-admin can't change it? Not normal as such, but not shocking either - I have zero experience with MP.  but I think I know where to look, let me check.

**Comment by jtsage** [comment]
I also wonder if it has anything to do with moving the save file into the savegame.  That might be controlled by the host only.  I could do what (I think) vehicle explorer does and save it in modSettings but under a savegame.  Let me give that a shot and I'll tag this issue with the upload / commit for testing.

**Comment by HurrycaneBE** [comment]
Positions save works now on mp. just only one time admin needed for a user to set the displaymode

**Comment by jtsage** [comment]
I'm wondering if that's because the game settings menu isn't there when you are a "regular" player? (like I said, not overly familiar with MP).  I could add those to general settings instead and see if that's better.

**Comment by HurrycaneBE** [comment]
the problem is on gamesettings menü , which u can access only when u authed as admin. maybe there anoher settings menu avail ? in german we habe - allgemeine einstellungen und spieleinstellungen ... ?

**Comment by jtsage** [comment]
Make sense.  I just pushed an update to the ZIP in the repo that moves all those settings to the other menu (allgemeine einstellungen), it might help

**Comment by HurrycaneBE** [comment]
Very fine - now settings of SI generally available. no more admin needed. Good Job ! Thank you

**Comment by jtsage** [comment]
Thank you so much for taking the time to work through this with me, it is very much appreciated!
